"""Builds body-map hotspots for every body image. See README.md."""
import json
import os
import sys

from PIL import Image, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
W, H = 288, 516
BANDS = ['kid', 'teen', 'young', 'adult', 'mid', 'senior', 'elder']


def load(name, view):
    path = os.path.join(ROOT, 'assets', 'bodies', f'body-{name}-{view}.webp')
    return Image.open(path).convert('RGB').resize((W, H))


def landmarks(im):
    px = im.load()
    corners = [px[2, 2], px[W - 3, 2], px[2, H // 2], px[W - 3, H // 2]]
    bg = tuple(sum(c[i] for c in corners) // 4 for i in range(3))
    m = [[sum(abs(px[x, y][i] - bg[i]) for i in range(3)) > 45 for x in range(W)] for y in range(H)]
    top = next(y for y in range(H) if sum(m[y]) > 3)
    feet = max(y for y in range(H) if sum(m[y][W // 4:3 * W // 4]) > 6)
    xs = [x for y in range(top, top + 20) for x in range(W) if m[y][x]]
    cx = sum(xs) / len(xs)
    y0 = top + int(0.45 * (feet - top))
    crotch = next(y for y in range(y0, feet) if not any(m[y][int(cx) - 1:int(cx) + 2]))
    width = 0
    for y in range(top + int(0.15 * (feet - top)), top + int(0.25 * (feet - top))):
        row = [x for x in range(W) if m[y][x]]
        if row:
            width = max(width, row[-1] - row[0])
    return dict(top=top, feet=feet, cx=cx, crotch=crotch, width=width)


def main():
    ref = json.load(open(os.path.join(HERE, 'reference.json')))
    adj = json.load(open(os.path.join(HERE, 'adjust.json')))
    names = [f'{b}-{s}' for b in BANDS for s in 'mf']
    lm = {}
    for n in names:
        for view in ['front', 'back']:
            key = f'{n}-{view}'
            lm[key] = landmarks(load(n, view))
            lm[key].update(adj['landmarks'].get(key, {}))

    models = {}
    for key, L in sorted(lm.items()):
        view = key.rsplit('-', 1)[1]
        R = lm[f'adult-m-{view}']
        pts = {}
        for mk, ps in ref[view].items():
            new = []
            for x, y in ps:
                if y <= R['crotch']:
                    ny = L['top'] + (y - R['top']) * (L['crotch'] - L['top']) / (R['crotch'] - R['top'])
                else:
                    ny = L['crotch'] + (y - R['crotch']) * (L['feet'] - L['crotch']) / (R['feet'] - R['crotch'])
                nx = L['cx'] + (x - R['cx']) * L['width'] / R['width']
                dx, dy = adj['deltas'].get(key, {}).get(mk, [0, 0])
                new.append([round(nx + dx), round(ny + dy)])
            pts[mk] = new
        models[key] = pts

    out = {
        '_note': 'Hotspot centers per body model, in a 288x516 frame (SPEC §5). Generated by scripts/hotspots from the SPEC reference points and checked by eye on all 28 images. Re-run the scripts when images change.',
        'frame': {'width': W, 'height': H},
        'reference': ref,
        'models': models,
    }
    with open(os.path.join(ROOT, 'src', 'features', 'bodymap', 'hotspots.json'), 'w') as f:
        json.dump(out, f, indent=1)

    if '--sheets' in sys.argv:
        outdir = sys.argv[sys.argv.index('--sheets') + 1]
        os.makedirs(outdir, exist_ok=True)
        for view in ['front', 'back']:
            sheet = Image.new('RGB', (W * 2 * 7, H * 2 * 2), 'white')
            for i, n in enumerate(names):
                im = load(n, view).resize((W * 2, H * 2))
                d = ImageDraw.Draw(im)
                for mk, ps in models[f'{n}-{view}'].items():
                    for x, y in ps:
                        d.ellipse([x * 2 - 6, y * 2 - 6, x * 2 + 6, y * 2 + 6], fill=(194, 62, 23), outline='white')
                        d.text((x * 2 + 8, y * 2 - 6), mk[:6], fill=(0, 0, 0))
                d.text((6, 6), n, fill=(0, 0, 0))
                sheet.paste(im, ((i // 2) * W * 2, (i % 2) * H * 2))
            sheet.save(os.path.join(outdir, f'hotspots-{view}.png'))


if __name__ == '__main__':
    main()
