// Builds supabase/seed.sql from supabase/seed/exercises.json (the single
// source of the prototype library). Run: npm run seed:build
// With --check, exits non-zero when seed.sql is out of date (used by tests).
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = JSON.parse(readFileSync(join(root, 'supabase/seed/exercises.json'), 'utf8'));
const target = join(root, 'supabase/seed.sql');

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const arr = (values, type) => `array[${values.map(q).join(', ')}]::${type}[]`;

export function buildSeed(exercises) {
  const lines = [
    '-- GENERATED by scripts/build-seed.mjs from supabase/seed/exercises.json. Do not edit.',
    '-- Prototype library: every exercise is a draft and never reaches users (SPEC §2.1).',
    '',
  ];
  for (const e of exercises) {
    lines.push(
      'insert into public.exercises (slug, name_i18n_key, cues_i18n_key, equipment, location, level,' +
        ' min_age_band, positions, contraindications, movement_pattern, session_parts, dose_type,' +
        ' loaded, unilateral, impact, media_provider, joint_movements, range_limit, rehab) values (' +
        [
          q(e.slug),
          q(`exercises.${e.slug}.name`),
          q(`exercises.${e.slug}.cues`),
          arr(e.equipment, 'text'),
          arr(e.location, 'public.training_location'),
          e.level,
          q(e.minAgeBand),
          arr(e.positions, 'public.position_ability'),
          arr(e.contraindications, 'text'),
          q(e.pattern),
          arr(e.parts, 'public.session_part'),
          q(e.dose),
          e.loaded,
          e.unilateral,
          e.impact,
          q('prototype'),
          `${q(JSON.stringify(e.joints ?? []))}::jsonb`,
          arr(e.rangeLimit ?? [], 'text'),
          e.rehab ?? false,
        ].join(', ') +
        ');',
    );
    for (const [key, role, emphasis] of e.muscles) {
      lines.push(
        `insert into public.exercise_muscles (exercise_id, muscle_key, role, emphasis) ` +
          `select id, ${q(key)}, ${q(role)}, ${emphasis} from public.exercises where slug = ${q(e.slug)};`,
      );
    }
    lines.push('');
  }
  return lines.join('\n');
}

const sql = buildSeed(source.exercises);
if (process.argv.includes('--check')) {
  const current = readFileSync(target, 'utf8');
  if (current !== sql) {
    console.error('supabase/seed.sql is out of date: run npm run seed:build');
    process.exit(1);
  }
} else {
  writeFileSync(target, sql);
  console.log(`wrote ${source.exercises.length} exercises to supabase/seed.sql`);
}
