import type { BodySex } from '../bodymap/images';

/**
 * Exercise demo clips by sex (Daniel, Phase 20): every video exists as a
 * woman's and a man's version, and a profile only ever sees its own. The
 * manifest is assets/prototype/videos.js (slug → { f, m, poster: { f, m } }), generated by
 * `npm run prototype:videos`; it is required only inside `if (__DEV__)`, so
 * release builds carry no clip until the reviewer approves (bundle:check).
 */
export type DemoSex = BodySex;
/** A bundled asset: a module id on native; on web a URL (video) or { uri } (image). */
export type DemoMedia = number | string | { uri: string };
type Entry = { f?: DemoMedia; m?: DemoMedia; poster?: { f?: DemoMedia; m?: DemoMedia } };
const isMedia = (v: unknown): v is DemoMedia =>
  typeof v === 'number' ||
  (typeof v === 'string' && v !== '') ||
  (typeof v === 'object' && v !== null && typeof (v as { uri?: unknown }).uri === 'string');
type Manifest = Record<string, Entry | string>;

function manifest(): Manifest {
  if (__DEV__) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require('../../../assets/prototype/videos.js') as Manifest;
  }
  return {};
}

/** The clip for this sex, or null. Never the other sex's clip. */
export function demoVideo(slug: string, sex: DemoSex | null): DemoMedia | null {
  if (!sex || slug === '__label') return null;
  const entry = manifest()[slug];
  const source = typeof entry === 'object' ? entry[sex] : undefined;
  return isMedia(source) ? source : null;
}

/**
 * The clip's poster (its starting image) for this sex, or null. Only next to
 * a clip of the same sex: never the other sex's picture.
 */
export function demoPoster(slug: string, sex: DemoSex | null): DemoMedia | null {
  if (!sex || slug === '__label') return null;
  const entry = manifest()[slug];
  if (typeof entry !== 'object' || !isMedia(entry[sex])) return null;
  const source = entry.poster?.[sex];
  return isMedia(source) ? source : null;
}

/**
 * Which demos a profile sees: its sex, else the body model it picked; null
 * means ask once ("Show exercise demos with"). Never guessed. Teens and 60+
 * use the adult model of their sex for now.
 */
export function demoSexFor(p: {
  sex?: 'f' | 'm' | null;
  bodyModel?: { sex?: BodySex };
}): DemoSex | null {
  if (p.sex === 'f' || p.sex === 'm') return p.sex;
  return p.bodyModel?.sex ?? null;
}
