import { publicEnv } from '@/lib/env';

import type { BodySex } from '../bodymap/images';

import { useReleasedLibraryStore } from './released';

/**
 * Exercise demo clips by sex (Daniel, Phase 20): every video exists as a
 * woman's and a man's version, and a profile only ever sees its own. (The
 * one exception lives in the data, not here: qc.json "otherSex" lists the
 * few clips Google Flow kept refusing, which the manifest fills with the
 * other sex's clip; Daniel, Oct 1, 2026.) The
 * manifest is assets/prototype/videos.js (slug → { f, m, poster: { f, m } }), generated by
 * `npm run prototype:videos`; it is required only inside `if (__DEV__)`, so
 * release builds carry no clip in the bundle (bundle:check). Released
 * exercises stream theirs from Supabase Storage instead (Phase 32).
 */
export type DemoSex = BodySex;
/**
 * A bundled asset (a module id on native; on web a URL or { uri }), or a
 * released clip from Supabase Storage, cached on the phone (`useCaching`).
 */
export type DemoMedia = number | string | { uri: string; useCaching?: boolean };
type Entry = { f?: DemoMedia; m?: DemoMedia; poster?: { f?: DemoMedia; m?: DemoMedia } };
const isMedia = (v: unknown): v is DemoMedia =>
  typeof v === 'number' ||
  (typeof v === 'string' && v !== '') ||
  (typeof v === 'object' && v !== null && typeof (v as { uri?: unknown }).uri === 'string');
type Manifest = Record<string, Entry | string>;

function manifest(): Manifest {
  if (__DEV__) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    return require('../../../assets/prototype/videos.js') as Manifest;
  }
  return {};
}

/**
 * Where released clips live (Phase 32, Daniel, Oct 3): the public
 * `exercise-media` bucket of this build's Supabase project, as
 * `<slug>.<f|m>.mp4` and `posters/<slug>.<f|m>.webp`. Null without a backend.
 */
export function mediaBase(): string | null {
  return publicEnv
    ? `${publicEnv.supabaseUrl.replace(/\/$/, '')}/storage/v1/object/public/exercise-media`
    : null;
}

/** A released exercise with Flow clips: the release script only sets these with both sexes. */
function released(slug: string): boolean {
  return useReleasedLibraryStore
    .getState()
    .rows.some(
      (r) => r.slug === slug && r.status === 'released' && r.media_provider === 'google_flow',
    );
}

/** The clip for this sex, or null. Never the other sex's clip. */
export function demoVideo(slug: string, sex: DemoSex | null): DemoMedia | null {
  if (!sex || slug === '__label') return null;
  const entry = manifest()[slug];
  const source = typeof entry === 'object' ? entry[sex] : undefined;
  if (isMedia(source)) return source;
  const base = mediaBase();
  // Downloaded once, then played from the phone's cache.
  return base && released(slug) ? { uri: `${base}/${slug}.${sex}.mp4`, useCaching: true } : null;
}

/**
 * The clip's poster (its starting image) for this sex, or null. Never the
 * other sex's picture. An exercise whose clip is not made yet can have the
 * poster alone (Daniel, Oct 2); the manifest only lists checked images.
 */
export function demoPoster(slug: string, sex: DemoSex | null): DemoMedia | null {
  if (!sex || slug === '__label') return null;
  const entry = manifest()[slug];
  const source = typeof entry === 'object' ? entry.poster?.[sex] : undefined;
  if (isMedia(source)) return source;
  const base = mediaBase();
  // expo-image keeps it in its disk cache.
  return base && released(slug) ? { uri: `${base}/posters/${slug}.${sex}.webp` } : null;
}

/**
 * Which demos a profile sees: its sex, else the body model it picked; null
 * means ask once ("Show exercise demos with"). Never guessed. Teens and 60+
 * use the adult model of their sex for now.
 */
export function demoSexFor(p: {
  sex?: 'f' | 'm' | null;
  bodyModel?: { sex?: BodySex };
}): DemoSex | null {
  if (p.sex === 'f' || p.sex === 'm') return p.sex;
  return p.bodyModel?.sex ?? null;
}
